# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20160503_0533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EMUser',
        ),
    ]
