# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20160504_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_shopping',
            name='purchased_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
